### ISSUE TITLE
Compatibilidade com o Demoiselle Framework 2.4.0

### ISSUE THREAD

**Issue by zyc** [demoiselle/certificate#1]
Até a próxima sexta-feira (dia 27/11/2013) será lançada a versão 2.4.0-RC1 do demoiselle-core e suas extensões. Seria interessante que vocês analisassem e compatibilizassem, caso necessário, o componente com esta prévia da versão 2.4.0 Final que será lançada em breve. Entre a versão RC e a Final não pretendemos incluir nenhuma nova funcionalidade, mudança estrutural ou quebra de compatibilidade.

**Comment by juliancesar** [comment]
Olá, vou fechar esta issue e caso ela ainda seja pertinente favor reabrir.
