### ISSUE TITLE
Erro na validação de PA AD-RB e AD-RT versão 2.1 no site do ITI

### ISSUE THREAD

**Issue by rsaulo** [demoiselle/certificate#12]
Olá, 

Estou utilizando o componente para geração de P7s e sempre que tento validar o arquivo assinado no site do ITI (https://verificador.iti.gov.br/verificador.xhtml) recebo a mensagem "Inconsistência no IdAaEtsSigPolicyIdentifier. Os resumos criptográficos do atributo e da PA não são os mesmos."

Tudo está OK  e normal, somente o atributo IdAaEtsSigPolicyIdentifier que parece com problemas, como pelo framework ele é derivado do arquivo DER acredito que esteja havendo algum problema ou com o arquivo DER ou com o algoritmo utilizado.

Alguma sugestão? Alguém já conseguiu validar ?

Obrigado!

**Comment by ednaraoliveira** [comment]
Olá rsaulo. 
Está usando a versão 2?
esse erro com o atributo é listado no relatório do ITI?
Acabei de testar com política 2.1 nas versões 1.0.12-SNAPSHOT e 2.0.1-SNAPSHOT.

Usei essa classe para testar: 
https://github.com/ednaraoliveira/example-certificate/blob/master/SECertificate/src/main/java/simple/example/linux/CertificateSignerLinux.java

**Comment by rsaulo** [comment]
Olá Ednara, obrigado pelo retorno.

Sim, estou com a 2.0, acabei descobrindo um pull request com uma alteração sobre isso e agora está OK para AD-RB.

O problema agora é no AD-RT, o que acho estranho uma vez que o framework pega os atributos de algortimo e hash da PA diretamente do DER.

Você conseguiu fazer um teste com AD-RT?

**Comment by ednaraoliveira** [comment]
Olá Saulo, 

Você conseguiu validar a RB agora pela manhã ? me parece que está ocorrendo alguma instabilidade no site do verificador. 
Quanto a RT estávamos em contato com ITI e eles lançaram uma nova versão do verificador, (1.3.3 anterior e 1.4 a nova) apresentando uma nova inconformidade, voltaremos a entrar em contato com eles.

**Comment by rsaulo** [comment]
Olá, 

Sim, consegui hoje cedo, mas agora está dando erro mesmo... ;)
O problema é mesmo no RT, ou o verificador, ou a PA (arquivo DER)...

Se você puder avisar aqui quando estiver OK eu ficaria muito agradecido mesmo!!!

Obrigado

**Comment by ednaraoliveira** [comment]
Aviso sim Saulo.

**Comment by rsaulo** [comment]
Parece que o site do ITI voltou, mas continua com o mesmo problema. Será que ninguém tentou validar um AD-RT com um carimbo ICP-Brasil ainda?

**Comment by ednaraoliveira** [comment]
Saulo, 
Acabei de verificar que está de volta. As inconformidades que o relatório do ITI apresentava em uma versão anterior eram outras. 
Agora incluíram inclusive o alerta, para o atributo que estava sendo invalidado antes:
"O atributo SiginingCertificateV2 não é permitido segundo o DOC-ICP-15, porem devido ao atributo SiginingCertificateV1 utilizar algorítmo de hash SHA-1, que não é mais recomendado na ICP-Brasil, o DOC-ICP-15 deverá ser atualizado em breve para permitir a utilização deste atributo."

Vou verificar a nova inconformidade e entrar em contato com eles para entender melhor o que está acontecendo.

**Comment by rsaulo** [comment]
Nesse caso tudo bem, mas o problema continuar com o atributo "IdAaEtsSigPolicyIdentifier", você já conseguiu validar uma assinatura AD-RT? Teria um exemplo de um P7s p/ me enviar? Se você quiser eu posso anexar aqui um P7s com AD-RT p/ vc tentar verificar se for o caso...

**Comment by jordanorc** [comment]
Algum retorno em relação à esta questão?Também está aparecendo pra mim: Inconsistência no IdAaEtsSigPolicyIdentifier. Os resumos criptográficos do atributo e da PA não são os mesmos. Sim, estou com usando a versão 2.0 com AD_RB.

**Comment by bfranzin** [comment]
Olá pessoal, boa noite!

Pra mim também está ocorrendo. Tentei com a versão 2.0.0 e com a 1.1.1 com AD_RB, ambas assinam normalmente, mas o erro ocorre não somente no verificador do ITI, mas também no da Receita Federal (A assinatura digital do documento fornecido não é válida. Motivo: Invalid algorithm specified.) e em outros dois verificadores privados (BRySigner e na lib ICPBravo), esses últimos não são opensource.

Não havia visto esse issue aqui e acabei postando uma pergunta no stackoverflow http://pt.stackoverflow.com/questions/180208/inconsist%c3%aancia-no-idaaetssigpolicyidentifier-demoiselle-certificate-pkcs7

Obrigado

**Comment by juliancesar** [comment]
Pessoal, estou entrando no projeto agora e a principal recomendação vinda da equipe é que seja utilizada a versão **1.1.2** do **demoiselle-certificate**, a versão 2.0 não possui versão oficial lançada.

**Comment by jordanorc** [comment]
Olá @juliancesar,

Acabei de testar na 1.1.2 e aparece a mesma mensagem no validador (Inconsistência no IdAaEtsSigPolicyIdentifier. Os resumos criptográficos do atributo e da PA não são os mesmos.). Poderia fazer um teste aí também?

Estou utilizando ADRBCMS_2_1.

**Comment by jordanorc** [comment]
Mais uma informação: compilei a versão 2.0.0-BETA2, nesta versão o problema parece ter sido resolvido. Já não aparece https://github.com/demoiselle/signer/issues/14 nem https://github.com/demoiselle/signer/issues/21.

**Comment by juliancesar** [comment]
Vamos por partes, preciso entender melhor o contexto:
* pelo que entendi você gerou um arquivo P7s com **ADRBCMS_2_1** e esta tentando validar no site do **ITI**, é isso?
* já tentou usar a **AD_RB_CADES_2_2**, pois fiz vários testes aqui e com esta política que é a que utilizamos no Serpro e tudo ocorreu bem validando no ITI

Meu ambiente:
* Ubuntu 12.04
* Token branco
* Java 1.8.0_121
* Versão 1.1.2 do demoiselle-certificate

Preciso saber mais sobre o seu ambiente:
* Sistema operacional
* Característica do token (branco, preto)
* Versão do Java
* Versão do componente

**Comment by jordanorc** [comment]
Olá @juliancesar,

- Pelo que entendi você gerou um arquivo P7s com ADRBCMS_2_1 e esta tentando validar no site do ITI, é isso? **Exatamente**

Vamos lá:

- Meu ambiente: Ubuntu 16.04
- Java:  1.8.0_121-b13
- Token: Preto 

Testes que fiz:

- Versão 1.1.2 do demoiselle-certificate com ADRBCMS_2_1: não valida
- Versão 1.1.2 do demoiselle-certificate com ADRBCMS_2_2: não valida
- Versão 2.0.0-BETA2 do demoiselle-signer (https://github.com/demoiselle/signer) com AD_RB_CADES_2_2: valida

Você utilizou o AD_RB_CADES_2_2 na versão 1.1.2? Não achei a classe nessa versão, só na 2.0.0-BETA2.

**Comment by juliancesar** [comment]
@bfranzin, favor abrir uma issue separada para o seu caso que parece ser outra coisa (Motivo: Invalid algorithm specified).

@rsaulo, fizemos outros testes e realmente existe um problema com o atributo **IdAaEtsSigPolicyId** na atual versão, pretendemos lançar uma versão **1.1.4** em breve contendo esta correção. Contudo é importante ressaltar que este atributo não invalida a sua assinatura.

**Comment by juliancesar** [comment]
Lançada a versão **1.2.0-RC1** para testes em desenvolvimento.

**Comment by juliancesar** [comment]
Algum retorno sobre o assunto?

**Comment by juliancesar** [comment]
Issue fechada por falta de retorno e caso o problema persista favor reabrir.

**Comment by EngBruno** [comment]
Desculpa por reabrir, mas estou enfrentando o seguinte problema.

Estou assinando documentos no formato CADES e utilizando a biblioteca do Demosello na versão 3.2.10 "org.demoiselle.signer","org.demoiselle.signer", e "org.demoiselle.signer" o ato de assinar e verificar dentro na minha aplicação esta funcionado normalmente. Para reforma os teste manuais, faço as verificações nas seguintes plataformas:

1.bryclound verificação
2.certisign
3.Assinador da SERPRO
4.E em uma plataforma da Europa (https://ec.europa.eu/cefdigital/DSS/webapp-demo)

Todos validam a assinatura como sendo correta. Porém o meu objetivo é validar no:

https://verificador.iti.gov.br/verificador.xhtml

Ele informa que houve um erro ao gerar relatório, somente isso. Alguém já enfrentou esse problema?
