### ISSUE TITLE
Erro de Validação em P7s assinado com signer 2.0.0

### ISSUE THREAD

**Issue by glauciosouthier** [demoiselle/certificate#14]
Pessoal:
assinando com a versão 2.0.0 assina e valida normalmente:
PKCS7Signer signer = PKCS7Factory.getInstance().factoryDefault();
            signer.setCertificates(keystore.getCertificateChain(alias));
            signer.setPrivateKey((PrivateKey) keystore.getKey(alias, null));
signer.setSignaturePolicy(PolicyFactory.Policies.AD_RB_CADES_2_1);
signer.setAttached(true);
byte[] signed = signer.doSign(content);
boolean checked = signer.check(null, signed);

Mas no site do ITI da a mensagem:
 Mensagem de erro:Não foi possível recuperar certificados do caminho de certificação 

Acredito que seja porque o certificado emitido pela Caixa não vem com a cadeia completa, apenas a CA imediatamente acima.
Já tivemos erro semelhante com certificado A1 ao acessar a Receita e só conecta incluindo as intermediárias. Mas no A3 (token) não tem como incluir.

**Comment by glauciosouthier** [comment]
Se for esse o problema teria como o assinador completar a cadeia no certificado antes de anexar ao p7s?

**Comment by juliancesar** [comment]
Olá @glauciosouthier, tente utilizar a versão **1.1.2** com **AD_RB_CADES_2_2**. A versão 2.0 do componente não tem versão final oficial e portanto não existe recomendação para utilização.

Faça o teste com a 1.1.2 e nos retorne.

**Comment by juliancesar** [comment]
Corrigindo, utilize a **ADRBCMS_2_2**. Aguardo.

**Comment by juliancesar** [comment]
Lançada a versão **1.2.0-RC1** para testes em desenvolvimento.

**Comment by juliancesar** [comment]
@glauciosouthier algum retorno sobre o assunto?

**Comment by glauciosouthier** [comment]
estou sem tempo para testar, assim que fizer o teste reporto os achados.

Em tempo: na validação no site do ITI os atributos estavam todos OK mas ele
dava a assinatura como inválida, não sei porque.

2017-02-24 11:00 GMT-03:00 Julian Cesar <notifications@github.com>:

**Comment by juliancesar** [comment]
@glauciosouthier este problema também já foi corrigido na issue #12. Favor testar;

**Comment by juliancesar** [comment]
Vou fechar a **issue**, e caso o problema persista favor reabrir.
