### ISSUE TITLE
Rever política de manutenção das Autoridades Certificadoras

### ISSUE THREAD

**Issue by joserenecampa** [demoiselle/certificate#19]
Além de utilizar a cadeia de certificados interna do componente, se faz necessário obter atualização de outros meios como por exemplo no site do próprio ITI. É possível também acessar a base de autoridades do Firefox através da API NSS.

**Comment by juliancesar** [comment]
Vamos manter a documentação desta implementação no seguinte endereço de Wiki:
https://github.com/demoiselle/certificate/wiki/Prioridade-de-Providers

**Comment by juliancesar** [comment]
Lançada a versão **1.2.0-RC1** para testes em desenvolvimento.
