### ISSUE TITLE
Inconsistência no IdAaEtsSigPolicyIdentifier

### ISSUE THREAD

**Issue by Osdeni** [demoiselle/certificate#22]
Boa tarde, tudo bem?

Ao assinar digitalmente um documento, ele funcionou em partes.
Usando o validador de assinaturas do ITI, ele interpretou a assinatura válida conforme MP 2.200-2/2001, porém ele acusa o erro no atributo IdAaEtsSigPolicyId, alguém sabe como resolver?

Segue o erro completo abaixo:
Nome do atributo:IdAaEtsSigPolicyId
Corretude:Inválido
Mensagem de erro:Inconsistência no IdAaEtsSigPolicyIdentifier. Os resumos criptográficos do atributo e da PA não são os mesmos.

Utilizei a versão 1.1.1-SNAPSHOT

**Comment by esaito** [comment]
Boa tarde.

A versão mais atual é a 1.2.0-RC1
Experimente com essa e caso ainda ocorra o erro, nos informe.

**Comment by Osdeni** [comment]
Resolvido, obrigado Emerson
