### ISSUE TITLE
Versão 1.2.0-RC3 não reconhece assinatura!

### ISSUE THREAD

**Issue by rfigueiredo83** [demoiselle/certificate#25]
Estou utilizando a versão 1.2.0-RC3 com a política ADRBCMS_2_2, porém ao verificar a assinatura no software "Bry Verificador" a assinatura é inválida. O software diz "Não foi encontrado os dados do certificado que realizou a assinatura".

Meu cliente utiliza justamente esse software para validar as assinaturas.

No software Arisp e no verificador do ITI, a assinatura aparece como válida.

Há algo errado com essa política 2.2?

Abraços

![assinatura1](https://cloud.githubusercontent.com/assets/26492231/24061391/0b619ce0-0b36-11e7-954e-cdfc3e764b19.png)
<img width="275" alt="captura de tela 2017-03-20 as 22 14 04" src="https://cloud.githubusercontent.com/assets/26492231/24128422/94c13f6e-0dba-11e7-845c-eaf4831a95ca.png">

**Comment by rfigueiredo83** [comment]
Alguem?

**Comment by juliancesar** [comment]
@rfigueiredo83, a principio as assinaturas estão corretas.

Contudo não ficaram claros alguns pontos, seguem eles:
1. existem 4 validadores (Bry, ITI, Arisp e Demoiselle), 3 deles estão validando a informação e você acredita que eles tenham algum problema?
2. nas versões anteriores do componente Certificate a assinatura era considerada válida na Bry?
3. existe algum detalhamento do erro no software da Bry?

Nós seguimos as especificações do ITI e acreditamos que o melhor local para fazer a validação é o próprio ITI.

**Comment by rfigueiredo83** [comment]
@juliancesar , obrigado pela resposta.

Sim, a assinatura está OK, porém o software Bry diz que **faltam os dados do certificado na assinatura**, conforme a imagem que anexei.

O Arisp, até onde eu sei, não verifica a política de assinatura utilizada e, com isso, não emite qualquer alerta sobre dados que seriam obrigatórios na assinatura.

Eu já testei com várias versões e o Bry sempre acusa que **faltam os dados do certificado na assinatura.** Muito estranho!!!

No verificador do ITI, por sua vez, a assinatura é perfeitamente validada.

Estou usando a política ADRB 2.2, onde define, no ponto 5.2.1.1.4 do DOC-15.03 "Certificados Obrigatórios do Caminho de Certificação": Para as versões 1.1, 2.0, 2.1 e 2.2: o certificado do signatário.

Estou tentando analisar se falta algum dado do certificado do signatário.

**Comment by juliancesar** [comment]
@rfigueiredo83, acreditamos que exista um problema no software da Bry, pois este mesmo problema já ocorreu em outros validadores, sugiro que entre em contato com a Bry e verifique o campo IdAaSigningCertificateV2 que é o atributo que armazena o certificado, nas versões anteriores este atributo era chamado IdAaSigningCertificate (sem o V2) e causou confusão.

**Comment by rfigueiredo83** [comment]
Perfeito, @juliancesar !

Vou entrar em contato com eles. Assim que conseguir uma resposta eu atualizo aqui.

Muito obrigado.

**Comment by joserenecampa** [comment]
@rfigueiredo83 existe outra hipótese para esse erro. O componente permite que você adicione, na hora da geração da assinatura, o atributo "br.gov.frameworkdemoiselle.certificate.signer.pkcs7.attribute.SigningCertificate". Ex:

signer.addAtribute(new SigningCertificate(x509));

Caso seja o seu caso e recentemente trocou para a política 2.2, altere seu código para:

// remova a linha
// signer.addAtribute(new SigningCertificateV2(x509));
// adicione:
signer.setCertificate(x509);

E deixe que o componente decida qual atributo criar, a partir da política selecionada.

Espero ter ajudado.

**Comment by rfigueiredo83** [comment]
Olá @joserenecampa , obrigado pela mensagem.

Acredito que não seja o meu caso...
//Parametrizando o objeto PKCS7Signer para assinatura desanexada.
PKCS7Signer signer = PKCS7Factory.getInstance().factoryDefault();
**signer.setCertificates(keystore.getCertificateChain(alias));**
signer.setPrivateKey((PrivateKey) keystore.getKey(alias, null));
signer.setSignaturePolicy(new ADRBCMS_2_2());

O único detalhe diferente dos exemplos daqui do Github é o fato de eu estar entregando ao assinador apenas o hash (e não o arquivo completo):

**signer.addAttribute(new MessageDigest(HASH DO ARQUIVO PRONTO));**

Eu não faço o download do arquivo completo no servidor. Pega o hash pronto. Acredito que isso não tenha nenhuma influencia no fato do Verificador Bry não encontrar os dados do certificado.

**Comment by joserenecampa** [comment]
Ok, neste caso então pode ser problema no software da Bry. Voce teria um arquivo assinado que dá esse erro lá no software da Bry?

**Comment by rfigueiredo83** [comment]
Tenho sim, @joserenecampa !
[teste.p7s.zip](https://github.com/demoiselle/certificate/files/860107/teste.p7s.zip)
Esse arquivo é validado perfeitamente no verificador do ITI e no Arisp, mas no Bry acusa assinatura inválida.

Entrei em contato com o suporte do Bry, vamos ver qual resposta consigo deles. Depois coloco aqui...

**Comment by rfigueiredo83** [comment]
Pessoal, apenas para atualizar a questão:

O suporte do Bry é muito evasivo! Não consegui nenhuma resposta concreta a respeito do problema que relatei acima.

Eu também não consegui analisar se o meu código está correto!!!

Obrigado ao @joserenecampa e @juliancesar pelas respostas.

**Comment by rfigueiredo83** [comment]
Depois de muita insistência, responderam que minha assinatura não contém o CRL (x509CRL), apenas o x509Certificate. Por essa razão o verificador deles acusa como inválida a assinatura.

Estão dizendo que o CRL precisa estar embutido na assinatura. Alguém teria algo a acrescentar em relação a isso?

Abraços,

**Comment by joserenecampa** [comment]
@rfigueiredo83 , a assinatura em questão é a de referencia básica (ADRB 2.2). A política diz que "pode" conter as referencias, mas não é obrigatório. As políticas que obrigam o uso dessa informação são: RV, RC e RA e o campo em questão é o "id-aa-ets-revocationRefs".
Segue o link do ITI que regulamenta essas políticas: http://www.iti.gov.br/images/twiki/URL/pub/Certificacao/DocIcp/docs13082012/DOC-ICP-15.03_-_Versao_7.3_REQ_DAS_POL_DE_ASSIN__DIG_NA_ICP-BRASIL.pdf

**Comment by rfigueiredo83** [comment]
Perfeito, @joserenecampa !

Concordo 100% contigo. O Bry está comendo bola!

Abraços!

**Comment by rsaulo** [comment]
Olá pessoal, me deparei com essa discussão e gostaria de contribuir, uma vez que já tivemos aqui na empresa essa mesma discussão, inclusivo com envolvimento do ICP-Brasil, uma vez que fomos questionados exatamente sobre a inclusão das LCRs para as políticas AD-RB e AD-RT. A posição OFICIAL do ICP-Brasil vai de encontro com o entendimento de todos aqui (tirando a empresa citada), ou seja, não faz o menor sentido incluir as LCRs no arquivo assinado se o perfil de assinatura não prevê isso.
Incluo na discussão um outro ponto mais técnico que não vi comentado que é o TAMANHO dos arquivos, não faz sentido nenhum eu assinar um arquivo de 10k e deixar o P7s com 10MB só porque eu tive que incluir dentro dele LCRs "gigantes", isso é no mínimo uma péssima definição de TI.
Cito abaixo o trecho relevante sobre esse ponto que nos foi enviado pelo ICP-Brasil em resposta à uma consulta pública feita por nós em 2014 quando tivemos essa discussão : 

_**"Cada tipo de Política de Assinatura procura atender necessidades específicas de aplicações ou processos de negócio conforme suas características.
No caso da AD-RB, trata-se de processos de negócio que exigem estrita segurança à autenticidade e integridade do documento e deve ser utilizada para consumo imediato ou de curto prazo.
A AD-RT incorpora o carimbo do tempo adicionando irretratabilidade do momento de sua geração.
Como essas PAs (AD-RB e AD-RT) não trazem contidos, obrigatoriamente, os valores ou referências dos certificados e informações de revogação (LCR ou OCSP), as validações posteriores requererão essas informações por meio externo, ou seja, o processo de negócio deve prever procedimento complementar para armazenamento externo de certificados e LCRs, para validações posteriores. Vale lembrar que existem outras PAs (AD-RV, AD-RC e AD-RA) para atender demandas de negócios que necessitem de preservação dos documentos assinados por longo prazo, independente de procedimento de preservação."**_

Abraços,
Rogério

**Comment by rfigueiredo83** [comment]
Pessoal, apenas para avisá-los que o Bry fez algumas modificações no verificador deles e agora as assinaturas estão sendo validadas normalmente.

Agradeço pelo tempo e respostas de todos que contribuíram para esta questão que eu levantei.

Abraços!

**Comment by juliancesar** [comment]
Obrigado a todos pela contribuição. Vou fechar a issue.

**Comment by lfchiaradia** [comment]
Analisando os comentários enviados nesta issue, tenho as seguintes considerações:

- Primeiramente gostaria de esclarecer que em nenhum momento, no ticket _**BRY#2017032110001672**_ aberto pelo usuário identificado como Rafael Figueiredo, foram mencionados os problemas encontrados na assinatura encaminhada, sendo assim, a [afirmativa](https://github.com/demoiselle/certificate/issues/25#issuecomment-289241484) encaminhada em 25/03/2017 pelo usuário @rfigueiredo83 não está correta. Até pelo fato de se tratar de uma assinatura de referência básica (ADRB), claramente não há sentido incluir a CRL. 

- Em resposta a este chamado, a equipe de suporte da BRy Tecnologia informou que os responsáveis pelo validador do ITI já foram contatados em outro momento, onde foram expostas as inconsistências encontradas no seu verificador de assinaturas. Reforçou-se que a solução disponibilizada pelo ITI para validação de assinaturas ainda se encontra em fase de desenvolvimento, portanto, as melhorias necessárias devem ser contempladas em futuras versões.

- As soluções disponibilizadas pela BRy Tecnolgia estão totalmente aderentes com os requisitos das políticas de assinatura digital na ICP-Brasil, descritas no DOC-ICP-15.03. 

- Neste [commit](https://github.com/demoiselle/signer/commit/1610700634b99f375f84ca8469fa99f120531af2#diff-9e2cc7fecac27287850ce8c64c5bbf82), foi realizada uma alteração na classe `SigningCertificateV2.java` que corrige o processo de geração da assinatura pela biblioteca.
