### ISSUE TITLE
Impossibilidade de internacionalização das mensagens de erro e log

### ISSUE THREAD

**Issue by laubstein** [demoiselle/certificate#3]
No commit 59a5e0c05463fcdfc1319f34f9be9eede8fc07bc é possível visualizar a impossibilidade de i18n e a falta de padrão nas mensagens de erro e log existentes:
- português utilizando acentuação
- português sem acentuação
- inglês
- erro de concordância

**Comment by juliancesar** [comment]
Esta atividade foi desenvolvida no novo componente Demoiselle Signer.

https://github.com/demoiselle/signer
