### ISSUE TITLE
Java 151 não funciona.

### ISSUE THREAD

**Issue by rafaelfigueiredo83** [demoiselle/certificate#33]
Alguém consegue assinar na versão 151 do Java 8?

O arquivo da assinatura fica com zero bytes.

**Comment by rafaelfigueiredo83** [comment]
Alguém com o mesmo problema?

**Comment by esaito** [comment]
Tem como ativar os logs da console do Java e postar o erro?
O Java que tenho é a 144 e funciona, ainda não testei com 151.

**Comment by rafaelfigueiredo83** [comment]
@esaito, fiz vários testes e o problema, pelo menos por aqui, era no momento de gerar o arquivo ZIP. Por alguma razão, o ZIP ficava corrompido. Fiz algumas mudanças e funcionou normalmente.

A versão 144 funcionava normalmetne.

Será que a versão 151 trouxe mudanças com o zip?

Abraços,

**Comment by esaito** [comment]
Deve ter alguma mudança. Fizeram um pull request sobre isso: https://github.com/demoiselle/certificate/pull/34

**Comment by emobtech** [comment]
Alguma previsão de quando será lançado uma nova versão com a correção?

**Comment by rafaelfigueiredo83** [comment]
@emobtech Se você comentar a linha que define o nível de compressão do Zip, vai funcionar:

zipOut.setLevel(0);

**Comment by esaito** [comment]
Já aceitamos o seu pull-request. Já pode testar usando a versão 1.2.2-SNAPSHOT. Assim que finalizarmos os testes lançaremos a versão final.
