### ISSUE TITLE
Falha no uso da MSCAPI - JRE 64 bits >= 1.6.0_00 < 1.6.0_38

### ISSUE THREAD

**Issue by laubstein** [demoiselle/certificate#4]
A camada MSCAPI não está disponível para as versões JRE 64 bits >= 1.6.0_00 < 1.6.0_38. Sugiro a correção da documentação e, se possível, desabilitar esta camada, gerando uma mensagem de WARN, quando a versão utilizada estiver no intervalo indicado.

Mais informações: [JRE 1.6.0_38 bug fixes](http://www.oracle.com/technetwork/java/javase/2col/6u38-bugfixes-1880999.html) - Bug ID [6931562](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=2215540)

**Comment by juliancesar** [comment]
Devido a issue (#20) que sobe a versão do Java 7 esta questão não é mais pertinente.
