### ISSUE TITLE
Novo verificador do ITI - Assinatura Inválida

### ISSUE THREAD

**Issue by rafaelfigueiredo83** [demoiselle/certificate#44]
O ITI atualizou o seu verificador e, agora, as assinaturas são dadas como inválidas.

https://verificador.iti.gov.br/

Falha ao construir o atributo: 1.2.840.113549.1.9.16.2.47 - Um dos atributos IssuerSerial do id-aa-SigningCertificate não está válido: General names

<img width="743" alt="captura de tela 2018-11-29 as 09 09 57" src="https://user-images.githubusercontent.com/5509029/49218251-1adc2580-f3b7-11e8-9d1c-f4ac2772d76e.png">
<img width="910" alt="captura de tela 2018-11-29 as 09 09 28" src="https://user-images.githubusercontent.com/5509029/49218252-1b74bc00-f3b7-11e8-8068-2d0f1df6dc57.png">
<img width="657" alt="captura de tela 2018-11-29 as 09 09 39" src="https://user-images.githubusercontent.com/5509029/49218253-1b74bc00-f3b7-11e8-9af4-99cc2fbcc59d.png">

**Comment by rafaelfigueiredo83** [comment]
Entendo que essa versão "certificate" está descontinuada, porém, por se tratar de uma falha e não de uma melhoria, abri esse chamado para tentar solucionar o problema, uma vez que podem existir projetos utilizando essa versão, assim como o meu, que precisam ser corrigidos.

Estou analisando o atributo obrigatório IdAaSigningCertificateV2 mas não encontro o problema.

**Comment by joserenecampa** [comment]
O componente apenas referencia o certificado do assinante no campo IdAaSiginngCertificateV2. Talvez o certificado não esteja com a formação correta no "General names" ou o validador do ITI está interpretando este campo erradamente.

**Comment by rafaelfigueiredo83** [comment]
@joserenecampa, teste com vários certificados. Todos com o mesmo problema.

**Comment by esaito** [comment]
as assinaturas passam na validação do Assinador SERPRO?

**Comment by rafaelfigueiredo83** [comment]
@esaito, o "Assinador SERPRO" reconhece a assinatura como válida. Porém, apenas ele.

O novo Arisp também não reconhece. Veja:

![img_2297](https://user-images.githubusercontent.com/5509029/49244854-edfc3280-f3f7-11e8-8606-bec2a3da5c32.jpg)

O problema é que o pessoal aqui usa o Arisp e o verificador do ITI. :(

Não estou conseguindo resolver por aqui. Parece que está faltando a referencia do certificado.

**Comment by esaito** [comment]
Neste caso a sua solução é fazer o upgrade para o Demoiselle-Signer.

**Comment by esaito** [comment]
O componente foi descontinuado.
