### ISSUE TITLE
Drivers do token WatchData com caminhos diferentes

### ISSUE THREAD

**Issue by emsouza** [demoiselle/certificate#5]
O driver para o token WatchData é mapeado por padrão para a pasta:

**/system32/WatchData/Watchdata Brazil CSP v1.0/WDPKCS.dll**

O driver do meu token se instala em uma pasta com o nome diferente:

**system32/WatchData/Watchdata ICP CSP v1.0/WDPKCS.dll**

Seria interessante adicinar esse segundo caminho para que todas as versões do driver funcionem.

**Comment by antoniolazaro** [comment]
No Mac OS é necessário instalar o OpenCS que não vem mais nativo. Na versão do Mac OS 10.11 (El Capitain), o Mac não permite escrita de aplicativos de terceiros nas pastas do sistema operacional, nem criação de links simbólicos.

Na classe br.gov.frameworkdemoiselle.certificate.keystore.loader.configuration.Configuration, onde são mantidas os drivers padrão, existem duas configurações:
/usr/lib/opensc-pkcs11.so e /usr/pkcs11/opensc-pkcs11.so. Porém com essa mudança de segurança do Mac é necessário adicionar o path: /usr/local/lib/opensc-pkcs11.so. 

Para instalar o opensc no Mac Os El Capitain (10.11) é necessário fazer download da versão 0.16 (https://sourceforge.net/projects/opensc/files/OpenSC/opensc-0.16.0/).

Tentei gerar o build do projeto, porém para fazer funcionar, seria necessário assinar os jar do módulo core com essa nova opção e não possível porque a versão gerada pelo build não é assinada. Não ficou claro como isso funciona, por isso, estou compartilhando a informação.

@emsouza para fazer essa implementação sua, basta adicionar essas novas entradas nessa mesma classe, mas o problema é que não consigo usar o jar gerado pelo build oficial do projeto.

**Comment by juliancesar** [comment]
Olá, vou fechar esta issue e caso ela ainda seja pertinente favor reabrir.
