### ISSUE TITLE
Execute Applet - ClassNotFoundException: org.bouncycastle.asn1.ASN1InputStream

### ISSUE THREAD

**Issue by ricardoborges** [demoiselle/certificate#9]
Estou seguindo este manual:

http://demoiselle.sourceforge.net/docs/components/certificate/reference/1.0.10/html_single/#d0e321

Compilo com sucesso o demoiselle-applet-customizada.jar, crio a pagina HTML conforme explicado. A applet roda com sucesso, lista meus certificados, mas quando clico em Executar, ele dispara este erro, como se não encontrasse a versão correta da lib bcprov-jdk15-1.45.jar. Estou usando todas as dependencias que baixei junto a dist bin "demoiselle-certificate-1.0.10"

java.lang.ClassNotFoundException: org.bouncycastle.asn1.ASN1InputStream

O que pode ser? Já tentei compilar com o jdk 5 e mesmo erro...

**Comment by ricardoborges** [comment]
Percebi que sem assinar a bcprov-jdk15-1.45.jar funcionou normalmente.

**Comment by ednaraoliveira** [comment]
Olá ricardo

Você fez esses passos da documentação?
- 5.10. Tratando os artefatos jar assinados por terceiros (http://demoiselle.sourceforge.net/docs/components/certificate/reference/1.0.10/html_single/#d0e857)
- 5.9. Incluindo os atributos no manifesto (http://demoiselle.sourceforge.net/docs/components/certificate/reference/1.0.10/html_single/#d0e839)
Ainda não tivemos nenhum erro semelhante a esse.

**Comment by ricardoborges** [comment]
Nara,

Obrigado pela observação. Ainda não por que estou num ambiente de desenvolvimento, mas percebi que será importante quando implantar.

Muito obrigado!

**Comment by juliancesar** [comment]
Olá, vou fechar esta issue e caso ela ainda seja pertinente favor reabrir.
